# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessuser',
            name='graduation_year',
        ),
    ]
