# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_program', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buy_program',
            new_name='your_details',
        ),
    ]
