# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-24 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy_program', '0005_auto_20190818_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='levels',
        ),
        migrations.AddField(
            model_name='details',
            name='level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
