# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-26 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_program', '0006_auto_20190824_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
