# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.TextField(blank=True, default='')),
                ('day2', models.TextField(blank=True, default='')),
                ('day3', models.TextField(blank=True, default='')),
                ('day4', models.TextField(blank=True, default='')),
                ('day5', models.TextField(blank=True, default='')),
                ('day6', models.TextField(blank=True, default='')),
                ('day7', models.TextField(blank=True, default='')),
            ],
        ),
    ]
