# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitness_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_ProgramsWeeks1to4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_focus', models.TextField()),
                ('monday', models.CharField(default='', max_length=254)),
                ('tuesday', models.CharField(default='', max_length=254)),
                ('wednesday', models.CharField(default='', max_length=254)),
                ('thursday', models.CharField(default='', max_length=254)),
                ('friday', models.CharField(default='', max_length=254)),
                ('saturday', models.CharField(default='', max_length=254)),
                ('sunday', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_ProgramsWeeks5to8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_focus', models.TextField()),
                ('monday', models.CharField(default='', max_length=254)),
                ('tuesday', models.CharField(default='', max_length=254)),
                ('wednesday', models.CharField(default='', max_length=254)),
                ('thursday', models.CharField(default='', max_length=254)),
                ('friday', models.CharField(default='', max_length=254)),
                ('saturday', models.CharField(default='', max_length=254)),
                ('sunday', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_ProgramsWeeks9to12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_focus', models.TextField()),
                ('monday', models.CharField(default='', max_length=254)),
                ('tuesday', models.CharField(default='', max_length=254)),
                ('wednesday', models.CharField(default='', max_length=254)),
                ('thursday', models.CharField(default='', max_length=254)),
                ('friday', models.CharField(default='', max_length=254)),
                ('saturday', models.CharField(default='', max_length=254)),
                ('sunday', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Fitness_Programs',
        ),
    ]
