# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_programs', '0002_auto_20190809_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitness_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_focus', models.TextField()),
                ('day1', models.TextField(blank=True, default='')),
                ('day2', models.TextField(blank=True, default='')),
                ('day3', models.TextField(blank=True, default='')),
                ('day4', models.TextField(blank=True, default='')),
                ('day5', models.TextField(blank=True, default='')),
                ('day6', models.TextField(blank=True, default='')),
                ('day7', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='', max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
                ('duratuion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='fitness_program',
        ),
        migrations.DeleteModel(
            name='Fitness_ProgramsWeeks1to4',
        ),
        migrations.DeleteModel(
            name='Fitness_ProgramsWeeks5to8',
        ),
        migrations.DeleteModel(
            name='Fitness_ProgramsWeeks9to12',
        ),
    ]
