# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_programs', '0003_auto_20190809_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitness_programs',
            old_name='duratuion',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day10',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day11',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day12',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day13',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day14',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day15',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day16',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day17',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day18',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day19',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day20',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day21',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day22',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day23',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day24',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day25',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day26',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day27',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day28',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day29',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day30',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day31',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day32',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day33',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day34',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day35',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day36',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day37',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day38',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day39',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day40',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day41',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day42',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day43',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day44',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day45',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day46',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day47',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day48',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day49',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day50',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day51',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day52',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day53',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day54',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day55',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day56',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day57',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day58',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day59',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day60',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day61',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day62',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day63',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day64',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day65',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day66',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day67',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day68',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day69',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day70',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day71',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day72',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day73',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day74',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day75',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day76',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day77',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day78',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day79',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day80',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day81',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day82',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day83',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day84',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fitness_programs',
            name='day9',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='day7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness_programs',
            name='level',
            field=models.CharField(default='', max_length=20),
        ),
    ]
